
I1=imread('im1.jpg')
A=imresize(I1, [1024 1024])
Aa=rgb2gray(A)
I2=imread('im2.jpg')
B=imresize(I2, [1024 1024])
Ba=rgb2gray(B)
figure
subplot(2,3,1),imshow(Aa),title('Image 1')
subplot(2,3,2),imshow(Ba),title('Image 2')
subplot(2,3,3),imshow(Aa+Ba),title('Addition')
subplot(2,3,4),imshow(Aa-Ba),title('Subtraction')
subplot(2,3,5),imshow(Aa.*Ba),title('Multiplication')
subplot(2,3,6),imshow(Aa./Ba),title('Division')
figure
subplot(2,3,1),imshow(Aa),title('Image 1')
subplot(2,3,2),imshow(Ba),title('Image 2')
subplot(2,3,3),imshow(bitand(Aa,Ba)),title('AND')
subplot(2,3,4),imshow(bitor(Aa,Ba)),title('OR')
subplot(2,3,5),imshow(bitxor(Aa,Ba)),title('XOR')
subplot(2,3,6),imshow(bitcmp(Aa)),title('NOT Image1')
figure
subplot(2,3,1),imshow(Aa),title('Image 1')
subplot(2,3,2),imshow(Ba),title('Image 2')
subplot(2,3,3),imshow(bitcmp(bitand(Aa,Ba))),title('NAND')
subplot(2,3,4),imshow(bitcmp(bitor(Aa,Ba))),title('NOR')
subplot(2,3,5),imshow(bitcmp(bitxor(Aa,Ba))),title('XNOR')
subplot(2,3,6),imshow(bitcmp(Ba)),title('NOT Image2')
figure
subplot(3,2,1),imshow(Ba),title('Image')
subplot(3,2,2),imhist(Ba),title('Histogram of Image')
subplot(3,2,3),histeq(Ba),title('Contrast Adjustment using Histogram Equaliser')
subplot(3,2,4),imhist(histeq(Ba)),title('Histogram of Contrasted Image')
subplot(3,2,5),imshow(imadjust(Ba)),title('Brightness Adjustment')
subplot(3,2,6),imhist(imadjust(Ba)),title('Histogram of Bright Image')